name: Build and Tests

on:
  push:
    branches:
      - "main"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: Sources

    - name: Build
      run: dotnet build --no-restore
      working-directory: Sources

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Sources
